export const AppRoutes = {
    root: '/',
    login: '/login',
    signUp: '/signUp',
    home: '/dashboard',
    verifyOtp: '/verify-otp',
    forgotPassword:'/forgot-password',
    resetPassword: '/reset-password/:token',
    settings:'/settings',
    appointments:'/appointments',
    familyMemeberSelector:'/familymemberselector',
    doctorsDetails:'/doctorDetails',
    registerFamily: '/registerFamily',
    paymentHistory: '/paymentHistory',
    createTicket:'/createTicket',
    ticketChat: '/ticketChat',
    inbox:'/inbox',
    prescription:'/prescription',
    aiDocotor: '/aiDocotor',
    aiBooth:'/aiBooth',
    prescriptionOverView: '/prescriptionOverView',
    patientRecods:"/patientRecords",
    patientRecorOverview:'/patientRecordOverview',
    earningWallet:"/earningWallet",
    appointmentRequest: '/appointmentRequest',
    appointmentOverview: '/appointmentOverview',
    doctorOnBoardingProgress:"/doctorOnBoardingProgress",
    doctorVerificationLanding: '/doctorVerificationLanding',
    doctorOnboardingForm:'/docotorOnboaringForm',
    slotMaker:'/slotMaker',
};
