    export * from './login';
    export * from './signup';
    export * from './home';
    export * from './verifyOtp';
    export * from './forgotPassword';
    export * from './resetPassword';
    export * from './settings';
    export * from './appointments';
    export * from './registerFamily';
    export * from './paymentHistory';
    export * from './createTicket'
    export * from './ticketChat';
    export * from './prescription';
    export * from './prescriptionOverView'
    export * from './patientsRecordList';
    export * from './patientRecordOverview';
    export * from './earningWallet';
    export * from './appointmentRequest';
    export * from './appointmentOverview';
    export * from './doctorOnBoardingProgress';
    export * from './doctorVerificationLanding';
    export * from './doctorOnboardingForm';
    export * from './createSlots'